pipeline {
    agent any

    tools {
        python 'Python 3'
    }

    environment {
        VENV_DIR = '.venv'
    }

    stages {
        stage('Checkout') {
            steps {
                git credentialsId: 'github-creds', url: 'https://github.com/NahomGulte/alx-backend-python.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                shiningPanda {
                    pythonName = 'Python 3'
                    nature = 'Shell script'
                    command = '''
                        python -m venv .venv
                        source .venv/bin/activate
                        pip install --upgrade pip
                        pip install -r requirements.txt
                    '''
                }
            }
        }

        stage('Run Tests') {
            steps {
                shiningPanda {
                    pythonName = 'Python 3'
                    nature = 'Shell script'
                    command = '''
                        source .venv/bin/activate
                        pytest --junitxml=pytest-report.xml
                    '''
                }
            }
        }

        stage('Publish Report') {
            steps {
                junit 'pytest-report.xml'
            }
        }
    }
}

